---
title: Jose Segura Blog
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
tagline: Front-end developer
description: Front-end developer y amante de compartir los conocimientos con cualquiera
  que esté dispuesto a aprender.
url: https://segux.github.io
baseurl: 
author:
  name: Jose Segura
  url: segux.github.io
paginate: 5
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
version: 3.4.1
sidebar_home_link: true
github:
  repo: https://github.com/segux
comments: true
disqus:
  shortname: segux
github_username: segux
include:
- ".htaccess"
